{{- $fullname := include "prosody.fullname" . -}}
{{- $labels := include "prosody.labels" . | nindent 4 -}}

{{- $clusterSecretStoreName := .Values.clusterSecretStoreName -}}
{{- range $key, $value := .Values.externalSecretsNames }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $fullname }}-{{ $key }}
  labels:
    {{- $labels }}
spec:
  refreshInterval: 30m
  secretStoreRef:
    name: {{ $clusterSecretStoreName }}
    kind: ClusterSecretStore
  data:
    - secretKey: {{ $key }}
      remoteRef:
        key: {{ $value.gcsmRef }}
{{- end }}