{{- range $key, $value := .Values.externalSecretsNames }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "prosody.fullname" . }}-{{ $key }}
  labels:
    {{- include "prosody.labels" . | nindent 4 }}

spec:
  refreshInterval: 30m
  secretStoreRef:
    name: {{ $.Values.clusterSecretStoreName }}
    kind: ClusterSecretStore
  data:
    - secretKey: {{ $key }}
      remoteRef:
        key: {{ $value.gcsmRef }}
{{- end }}